// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreatePostReq struct {
	BoardId int64  `json:"board_id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type GetPostReq struct {
	Id int64 `path:"id"`
}

type ListPostsReq struct {
	BoardId  int64 `form:"board_id,optional"`
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"page_size,default=10"`
}

type ListPostsResp struct {
	List     []PostResp `json:"list"`
	Total    int64      `json:"total"`
	Page     int64      `json:"page"`
	PageSize int64      `json:"page_size"`
}

type PostResp struct {
	Id           int64  `json:"id"`
	BoardId      int64  `json:"board_id"`
	UserId       int64  `json:"user_id"`
	Title        string `json:"title"`
	Content      string `json:"content"`
	Status       string `json:"status"`
	IsPinned     bool   `json:"is_pinned"`
	IsLocked     bool   `json:"is_locked"`
	ViewCount    int64  `json:"view_count"`
	LikeCount    int64  `json:"like_count"`
	CommentCount int64  `json:"comment_count"`
	CreatedAt    string `json:"created_at"`
}
