// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: forum.proto

package server

import (
	"context"

	"forum-rpc/internal/logic"
	"forum-rpc/internal/svc"
	"forum-rpc/pb/pb"
)

type ForumServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedForumServer
}

func NewForumServer(svcCtx *svc.ServiceContext) *ForumServer {
	return &ForumServer{
		svcCtx: svcCtx,
	}
}

func (s *ForumServer) CreatePost(ctx context.Context, in *pb.CreatePostReq) (*pb.CreatePostResp, error) {
	l := logic.NewCreatePostLogic(ctx, s.svcCtx)
	return l.CreatePost(in)
}

func (s *ForumServer) ListPosts(ctx context.Context, in *pb.ListPostsReq) (*pb.ListPostsResp, error) {
	l := logic.NewListPostsLogic(ctx, s.svcCtx)
	return l.ListPosts(in)
}

func (s *ForumServer) GetPost(ctx context.Context, in *pb.GetPostReq) (*pb.GetPostResp, error) {
	l := logic.NewGetPostLogic(ctx, s.svcCtx)
	return l.GetPost(in)
}
