// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: forum.proto

package forum

import (
	"context"

	"forum-rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreatePostReq  = pb.CreatePostReq
	CreatePostResp = pb.CreatePostResp
	GetPostReq     = pb.GetPostReq
	GetPostResp    = pb.GetPostResp
	ListPostsReq   = pb.ListPostsReq
	ListPostsResp  = pb.ListPostsResp
	PostItem       = pb.PostItem

	Forum interface {
		CreatePost(ctx context.Context, in *CreatePostReq, opts ...grpc.CallOption) (*CreatePostResp, error)
		ListPosts(ctx context.Context, in *ListPostsReq, opts ...grpc.CallOption) (*ListPostsResp, error)
		GetPost(ctx context.Context, in *GetPostReq, opts ...grpc.CallOption) (*GetPostResp, error)
	}

	defaultForum struct {
		cli zrpc.Client
	}
)

func NewForum(cli zrpc.Client) Forum {
	return &defaultForum{
		cli: cli,
	}
}

func (m *defaultForum) CreatePost(ctx context.Context, in *CreatePostReq, opts ...grpc.CallOption) (*CreatePostResp, error) {
	client := pb.NewForumClient(m.cli.Conn())
	return client.CreatePost(ctx, in, opts...)
}

func (m *defaultForum) ListPosts(ctx context.Context, in *ListPostsReq, opts ...grpc.CallOption) (*ListPostsResp, error) {
	client := pb.NewForumClient(m.cli.Conn())
	return client.ListPosts(ctx, in, opts...)
}

func (m *defaultForum) GetPost(ctx context.Context, in *GetPostReq, opts ...grpc.CallOption) (*GetPostResp, error) {
	client := pb.NewForumClient(m.cli.Conn())
	return client.GetPost(ctx, in, opts...)
}
