// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"forum-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/forum/posts",
				Handler: CreatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/forum/posts",
				Handler: ListPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/forum/posts/:id",
				Handler: GetPostHandler(serverCtx),
			},
		},
	)
}
